[package]
name = "sidetree"
version = "0.1.0"
authors = ["topisani <topisani@hamsterpoison.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.14"
termion = "1.5"
unicode-width = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
combine = "4.5.2"
